### ISSUE TITLE
allow custom appender

### ISSUE THREAD

**Issue by xxx** [minodes/sinatra-logger#10]
Hi,

Right now when configuring logging, the `logger` method [hard codes the appender to be a normal file](https://github.com/minodes/sinatra-logger/blob/2f08aed34f63c6d06f63c22799c0588f9fca1ad8/lib/sinatra/logger.rb#L47), but I'd like more control over that (in my case I'm running in a container so I want to log to stdout).

**Comment by jtara** [comment]
If on Linux, use `'dev/stdout`'.

Works for me!

**Comment by devyhia** [comment]
@xxx  Sorry for the late reply!
@jtara Thanks for your response. I would also like to add your comment to the README for people who want to log to stdout.

Personally, I would always prefer to log to a file (or a service like AWS CloudWatch) and keep tailing that file for what I am looking for. Something as follows (assuming your system logs to development.log):
```
$ tail -f development.log

// or

$ tail -100f development.log   // where 100 shows the last 100 lines in your log plus following the incoming stream of logs
```

@xxx Do you still need any help? If not, I would close this ticket for now. Feel free to open the ticket again if more help is needed.

**Comment by jtara** [comment]
Followup: when using sinatra-logger in the IBM Cloud Foundry Sinatra environment, you can indeed drop the recommended heroku/rails12factor Gem.

FYI, in the Cloud Foundry environment, any output to stdout/stderr is by default captured to Loggregator. 

https://docs.cloudfoundry.org/devguide/deploy-apps/streaming-logs.html#writing

As it is typical to run multiple instances, Loggregator combines the output from multiple instances to a single log stream. Storage per instance is limited, and so it would both be inconvenient and face problems with limited resources to log to a file.

In the case of IBM's implementation, specifically, the Loggregator stream is further passed on to Kibana. (There is a free tier with retention period of a few days, or a paid tier.) There is a function in the IBM Cloud (ex-Bluemix) CLI to tail the stream remotely.

Certainly, an application could use an API to log directly to Loggregator, Kibana, both, or other logging solutions. But since there's a decent default that I am happy with, I prefer to keep it simple. When I run locally for development/test, I can choose to redirect or tee stdout to a file, but typically just tail in a terminal application with a history feature (iTerm2).

Thought it would be useful for you to understand a bit more why somebody would prefer to log to STDOUT. Yes, please add the workaround to the docs, it will help others in the same types of environments.
